[package]
name = "debcargo"
version = "1.3.0"
authors = [
 "Josh Triplett <josh@joshtriplett.org>",
 "Ximin Luo <infinity0@debian.org>",
 "Vasudev Kamath <vasudev@copyninja.info>"]
license = "MIT/Apache-2.0"
repository = "https://anonscm.debian.org/git/pkg-rust/debcargo.git"
description = "Create a Debian package from a Cargo crate."

[dependencies]
cargo = "0.24"
clap = "2.18"
chrono = "0.4"
error-chain = "0.11"
flate2 = "1"
itertools = "0.7"
regex = "0.2"
semver = "0.8" # forced to be 0.8 because of cargo 0.24, else API type mismatch due to versions
semver-parser = "0.7"
tar = "0.4"
tempdir = "0.3"
walkdir = "2"
ansi_term = "0.10"
serde = "1.0"
serde_derive = "1.0"
textwrap = "0.9"
toml = "0.4"
git2 = "0.6"
