[package]
name = "debcargo"
version = "1.0.0"
authors = ["Josh Triplett <josh@joshtriplett.org>"]
license = "MIT/Apache-2.0"
description = "Create a Debian package from a Cargo crate."

[dependencies]
cargo = "0.14"
clap = "2.18"
chrono = "0.2.22"
error-chain = "0.7.1"
flate2 = "0.2"
itertools = "0.5"
regex = "0.1"
semver = "0.5"
semver-parser = "0.6"
tar = "0.4.9"
tempdir = "0.3"
walkdir = "1"
